spring.main.allow-bean-definition-overriding=true

spring.application.name=AssetTracker

server.port=${SERVER_PORT:8080}

# spring.mongodb.uri=mongodb://app_user:pwd12345@localhost:27017/?authSource=asset_tracker_db
spring.mongodb.host=${MONGODB_HOST:localhost}
spring.mongodb.port=${MONGODB_PORT:27017}
spring.mongodb.database=${MONGODB_DATABASE:support_desk_db}
spring.mongodb.authentication-database=${MONGODB_AUTHENTICATION_DATABASE:support_desk_db}
spring.mongodb.username=appuser
spring.mongodb.password=appuser123

spring.data.mongodb.auto-index-creation=true

spring.jackson.serialization.indent-output=true
spring.web.error.include-message=always
spring.web.error.include-binding-errors=always
spring.web.error.include-stacktrace=always

# JWT configuration
app.jwt.secret=supersecretkey_for_hmac_that_must_be_at_least_32_bytes_long_for_HS256
app.jwt.expiration-minutes=60

logging.level.root=INFO
logging.level.com.example.assettracker=DEBUG
logging.level.com.example.supportdesk=DEBUG

spring.output.ansi.enabled=always